language: node_js

node_js:
  - "10"
  - "12"

cache:
  pnpm: true
  directories:
    - node_modules

install:
  - npm install -g pnpm
  - pnpm i

script:
  - pnpm build
  - pnpm check:webpack
  - pnpm check:browserify
  - pnpm check:vanillajs